# Generated by Django 5.2.4 on 2025-07-17 18:29

from django.contrib.auth.hashers import make_password
from django.db import migrations

USERNAMES = ["mcastanho", "ftrocado", "jsobreira", "jsoares", "lprogano", "lluzio", "moliveira", "pesteves", "tcovas"]


def create_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    password = make_password("a1s2d3-f4")

    for username in USERNAMES:
        User.objects.create(username=username, password=password)


def delete_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=USERNAMES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_users, delete_users),
    ]
