version: "3.9"

services:
  backend:
    build: .
    command: ./start.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./staticfiles:/app/staticfiles

networks:
  app-network:
