# Generated by Django 5.2.4 on 2025-07-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="quizzes.categorygroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "constraints": [models.UniqueConstraint(fields=("name", "group"), name="unique_quiz_season_week")],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season", models.PositiveSmallIntegerField()),
                ("week", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name_plural": "quizzes",
                "constraints": [models.UniqueConstraint(fields=("season", "week"), name="unique_quiz_season_week")],
            },
        ),
        migrations.CreateModel(
            name="QuizPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="parts", to="quizzes.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                (
                    "quiz_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="quizzes.quizpart"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statement", models.TextField(max_length=1000)),
                ("answer", models.TextField(max_length=255)),
                ("is_box", models.BooleanField(default=False)),
                ("categories", models.ManyToManyField(related_name="questions", to="quizzes.category")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="quizzes.topic"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="quizpart",
            constraint=models.UniqueConstraint(fields=("quiz", "sequence"), name="unique_part_per_quiz_sequence"),
        ),
    ]
