# Generated by Django 5.2.4 on 2025-07-04 02:23

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model("quizzes", "Category")
    categories = [
        "Architecture",
        "Basketball",
        "Biology",
        "Botany",
        "Business",
        "Celebrities",
        "Chemistry",
        "Cinema",
        "Computers",
        "Design",
        "Engineering",
        "Entertainment",
        "Finance",
        "Football",
        "Geography",
        "History",
        "Journalism",
        "Literature",
        "Mathematics",
        "Media",
        "Music",
        "Mythology",
        "Philosophy",
        "Politics",
        "Recreation",
        "Science",
        "Sociology",
        "Sports",
        "Technology",
        "Travel",
        "Wellness",
    ]
    Category.objects.bulk_create([Category(name=name) for name in categories])


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=migrations.RunPython.noop),
    ]
