# Generated by Django 5.2.4 on 2025-07-17 18:17

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20250704_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='ppt_file',
            field=models.FileField(blank=True, help_text='Optional PowerPoint file for this quiz part', null=True, upload_to=quizzes.models.ppt_upload_path),
        ),
    ]
