# Generated by Django 5.2.4 on 2025-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_quizpart_ppt_file"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="category", name="unique_category_name_group"),
        migrations.AlterField(model_name="quiz", name="week", field=models.CharField(max_length=10)),
        migrations.AlterUniqueTogether(name="category", unique_together={("name", "group")}),
    ]
