# Generated by Django 5.2.4 on 2025-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0004_remove_category_unique_category_name_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category", name="description", field=models.CharField(max_length=1024, null=True)
        ),
    ]
