# Generated by Django 5.2.4 on 2025-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="description", field=models.CharField(blank=True, max_length=1024, null=True)
        ),
    ]
